# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-05 15:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hex', models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator(code=None, message=b'Not a valid HEX colour', regex=b'(^[A-Fa-f0-9]{6}$|^[A-Fa-f0-9]{3})$'), django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(6)])),
            ],
        ),
    ]
