# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-05 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pallette', '0002_pallette'),
    ]

    operations = [
        migrations.AddField(
            model_name='colour',
            name='pallete',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pallette.Pallette'),
            preserve_default=False,
        ),
    ]
